//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password and new password can not be same..
        /// </summary>
        public static string ChangePasswprd {
            get {
                return ResourceManager.GetString("ChangePasswprd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} ({1}) is already exist!.
        /// </summary>
        public static string ColumnExist {
            get {
                return ResourceManager.GetString("ColumnExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This selected combination is already exist!.
        /// </summary>
        public static string CombinationExist {
            get {
                return ResourceManager.GetString("CombinationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Save Change Failed.
        /// </summary>
        public static string DataInsertOrUpdateFailed {
            get {
                return ResourceManager.GetString("DataInsertOrUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Save Change Successfully.
        /// </summary>
        public static string DataInsertOrUpdateSuccessfully {
            get {
                return ResourceManager.GetString("DataInsertOrUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application database name is not define!.
        /// </summary>
        public static string DbName {
            get {
                return ResourceManager.GetString("DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBPassword name is not define in web config!.
        /// </summary>
        public static string DbPwd {
            get {
                return ResourceManager.GetString("DbPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBServer name is not define in web config!.
        /// </summary>
        public static string DbServerName {
            get {
                return ResourceManager.GetString("DbServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBUser name is not define in web config!.
        /// </summary>
        public static string DbUserName {
            get {
                return ResourceManager.GetString("DbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0} selected..
        /// </summary>
        public static string DuplicateSelection {
            get {
                return ResourceManager.GetString("DuplicateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations assemblies is not configure in web.config file!.
        /// </summary>
        public static string EfConfiguration {
            get {
                return ResourceManager.GetString("EfConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} Email Not Found.
        /// </summary>
        public static string EmailAddressMissing {
            get {
                return ResourceManager.GetString("EmailAddressMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempted.
        /// </summary>
        public static string InvalidAttempted {
            get {
                return ResourceManager.GetString("InvalidAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  is null..
        /// </summary>
        public static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        public static string LoginFailError {
            get {
                return ResourceManager.GetString("LoginFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully completed.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found!.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password will expire within {0} days..
        /// </summary>
        public static string PasswordExpireAlert {
            get {
                return ResourceManager.GetString("PasswordExpireAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record no longer exists..
        /// </summary>
        public static string RecordNoLonger {
            get {
                return ResourceManager.GetString("RecordNoLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successfully completed.
        /// </summary>
        public static string RegistrationSuccessfully {
            get {
                return ResourceManager.GetString("RegistrationSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same {0} already exist..
        /// </summary>
        public static string SameExist {
            get {
                return ResourceManager.GetString("SameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} SMTP configuration not found.
        /// </summary>
        public static string SMTPConfigNotFound {
            get {
                return ResourceManager.GetString("SMTPConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Authentication Token!.
        /// </summary>
        public static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authentication token is locked!.
        /// </summary>
        public static string TokenLocked {
            get {
                return ResourceManager.GetString("TokenLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/user/.
        /// </summary>
        public static string UserImageUrl {
            get {
                return ResourceManager.GetString("UserImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your userId is locked!.
        /// </summary>
        public static string UserLocked {
            get {
                return ResourceManager.GetString("UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username {0} is invalid..
        /// </summary>
        public static string UsernameInvalid {
            get {
                return ResourceManager.GetString("UsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not available.
        /// </summary>
        public static string UserNotAvailable {
            get {
                return ResourceManager.GetString("UserNotAvailable", resourceCulture);
            }
        }
    }
}
